# Generated by Django 3.1.3 on 2023-02-24 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(default='')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('temporada', models.TextField(default='')),
                ('genero', models.TextField(default='')),
                ('capitulos', models.SmallIntegerField(default=0)),
                ('estudio', models.TextField(default='')),
                ('director', models.TextField(default='')),
                ('animacion', models.CharField(default='', max_length=2)),
                ('formato', models.TextField(default='')),
                ('adaptacion', models.TextField(default='')),
            ],
        ),
    ]
