# Generated by Django 3.1.3 on 2023-02-24 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cap',
            name='fecha',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
