# Generated by Django 3.1.3 on 2023-02-24 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0002_auto_20230224_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cap',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
