# Generated by Django 3.1.3 on 2023-05-26 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0005_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='cap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caps', to='caps.cap'),
        ),
    ]
