apiVersion: v1
kind: ConfigMap
metadata:
 name: yacruz-config
 labels:
   app: postgres
data:
 DEV_SECRET_KEY: MY_DEV_SECRET_KEY
 DEV_DATABASE: MY_DEV_DATABASE
 DEV_USER: MY_DEV_USER
 DEV_PASSWORD: MY_DEV_PASSWORD
 DEV_HOST: MY_DEV_HOST
 DEV_PORT: MY_DEV_PORT

 PROD_SECRET_KEY: yacruz
 PROD_DATABASE: ocyllrdx
 PROD_USER: ocyllrdx
 PROD_PASSWORD: OHiono9-MLpEfQKk6dHl2vnvSUfPB759
 PROD_HOST: mahmud.db.elephantsql.com
 PROD_PORT: "5432"
